- id: chrome-extension-increment-version
  name: increment chrome extension version
  description: This hook increments the version in the manifest.json of your chrome extension.
  entry: chrome-extension-increment-version
  language: python
  types: [text]
  pass_filenames: false
  always_run: true
